### ISSUE TITLE
Not working under ubuntu 20.04

### ISSUE THREAD

**Issue by kaxapo** [jeanthom/linux-fbx#1]
Hello i tried to install this kernel on ubuntu 20.04 but when i choose to boot the kernel on the grub menu i'm unable to boot. I get an error message saying that the root disk where the ubuntu is installed does not exist and also the usb keyboard does not work when i get the initramfs prompt.

**Comment by jeanthom** [comment]
Uh... I'm pretty sure this repository is NOT for you - are you intending to run this kernel on a PC or on a French ISP gateway?

**Comment by kaxapo** [comment]
> Uh... I'm pretty sure this repository is NOT for you - are you intending to run this kernel on a PC or on a French ISP gateway?

I have a Freebox V6 and im trying to install the kernel on a PC running ubuntu 64 bits for testing purposes.

**Comment by jeanthom** [comment]
Ok then, this might actually be for you - I'm not sure however why you'd want to run it on an x86 PC since most of the changes I ported to Linux 4.4 were mostly driver and device tree changes.

Have you tried running the stock Linux 4.4 on Ubuntu 20.04? Have you checked the .config to ensure all the drivers you need for your hardware are there? Are you trying to run this kernel on bare metal or inside a hypervisor?

**Comment by kaxapo** [comment]
> Ok then, this might actually be for you - I'm not sure however why you'd want to run it on an x86 PC since most of the changes I ported to Linux 4.4 were mostly driver and device tree changes.
> 
> Have you tried running the stock Linux 4.4 on Ubuntu 20.04? Have you checked the .config to ensure all the drivers you need for your hardware are there? Are you trying to run this kernel on bare metal or inside a hypervisor?

Hello so i do not tried to install the stock kernel 4.4 before installing the Freebox kernel.

I'm trying to run this outside VM in a real pc config.

When i compile the kernel i got two errors when i run "make" command the first error is "509 certificate" and the second is a "wireless card drive winch stops the compilation" i fixed this by changing the value of CONFIG_SYSTEM_TRUSTED_KEYS = "". to empty and to solve the wireless driver problem when compiling i needed to run "make menu config" after i disable Wireless LAN i save it than i run "make" it compiles fine without any errors but when it finishes the compilation. I run "make install" and i get a weird error the "make install" tries to create a temporary folder and it outputs an error of a file. I dont remember well but i think its (modules.builtin.o) i get two errors but the installation proceeds and it creates the kernel but when i reboot the pc and choose the freebox keenel i land on busybox/initrams and if i try to write something with my keyboard it does not work so i need to turn of the pc and boot on the normal kernel.


If you want i can try again and post here all the errors i get.


Other thing i just realized its that on the kernel makemenu config the ext2 storage was not enabled and my harddrive where ubuntu is installed is ext2. Do you think it's because of this that i'm unable to boot into ubuntu?

Thanks


EDIT: (These are the errors i get when i "make install" after the compilation ends


root@kaxapo:/home/kaxapo/Téléchargements/linux-fbx-fbx-v4.4# make install
sh ./arch/x86/boot/install.sh 4.4.194 arch/x86/boot/bzImage \
	System.map "/boot"
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.4.194 /boot/vmlinuz-4.4.194
run-parts: executing /etc/kernel/postinst.d/dracut 4.4.194 /boot/vmlinuz-4.4.194
dracut: Generating /boot/initrd.img-4.4.194
depmod: WARNING: could not open modules.builtin at /var/tmp/dracut.KPuBMz/initramfs/lib/modules/4.4.194: No such file or directory
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.4.194 /boot/vmlinuz-4.4.194
update-initramfs: Generating /boot/initrd.img-4.4.194
cat: /var/tmp/mkinitramfs_cwTFcV/lib/modules/4.4.194/modules.builtin: Aucun fichier ou dossier de ce type
depmod: WARNING: could not open modules.builtin at /var/tmp/mkinitramfs_cwTFcV/lib/modules/4.4.194: No such file or directory
Warning: Not updating LILO; /etc/lilo.conf not found!

**Comment by jeanthom** [comment]
> Hello so i do not tried to install the stock kernel 4.4 before installing the Freebox kernel.

I urge you to try this before going any further. Ubuntu 20.04 LTS is based on the 5.4 kernel, I could imagine some incompatibilities from the userland with 4.4 kernels. I had some degree of success with a Debian userland initramfs.

> I'm trying to run this outside VM in a real pc config.

May I ask you what you are trying to achieve in this configuration?

> When i compile the kernel i got two errors when i run "make" command the first error is "509 certificate" and the second is a "wireless card drive winch stops the compilation" i fixed this by changing the value of CONFIG_SYSTEM_TRUSTED_KEYS = "". to empty and to solve the wireless driver problem when compiling i needed to run "make menu config" after i disable Wireless LAN i save it than i run "make" it compiles fine without any errors but when it finishes the compilation. I run "make install" and i get a weird error the "make install" tries to create a temporary folder and it outputs an error of a file. I dont remember well but i think its (modules.builtin.o) i get two errors but the installation proceeds and it creates the kernel but when i reboot the pc and choose the freebox keenel i land on busybox/initrams and if i try to write something with my keyboard it does not work so i need to turn of the pc and boot on the normal kernel.

Your configuration looks inadequate for your PC configuration. I would recommend you to start from scratch and add/remove modules to your liking.

> Other thing i just realized its that on the kernel makemenu config the ext2 storage was not enabled and my harddrive where ubuntu is installed is ext2. Do you think it's because of this that i'm unable to boot into ubuntu?

Yes, definitively. You also gotta make sure that ALL the drivers for your motherboard are enabled.

**Comment by kaxapo** [comment]
Did you successfully installed this kernel and booted on it ? 

1: im trying to install the kernel for testing purposes (btw i tried installing the stock linux 4.4 but it did not worked, one strange thing its that when i compile and make install the freebox kernel the make install does not install the linux headers for the 4.4.194 version)

2: Im running this on a real pc and not on a vm for facility.


3:  i have intel i5 9900k and i have an amd rx 580 gpu.

4: trying to enable the ext2 filesystem on the makemenu config did not fixed anything.


What linux do you used for compiling this kernel?

**Comment by jeanthom** [comment]
> Did you successfully installed this kernel and booted on it ?

No, actually I was meaning to do it this week-end... JK yes I got it to work on a Freebox. Never tried on a PC.

> 1: im trying to install the kernel for testing purposes (btw i tried installing the stock linux 4.4 but it did not worked, one strange thing its that when i compile and make install the freebox kernel the make install does not install the linux headers for the 4.4.194 version)
> 2: Im running this on a real pc and not on a vm for facility.

I'm genuinely curious to learn why you insist on running this kernel on a PC. I can't think of a single reason to do it. Let me ask you again why you are trying to do this?
 
> 3: i have intel i5 9900k and i have an amd rx 580 gpu.

Linux 4.4.194 came out after your CPU came out, so there's a pretty good chance this is not what's causing compatibility issues. Maybe a missing chipset driver or something like that? I barely know anything about personal computers.

> 4: trying to enable the ext2 filesystem on the makemenu config did not fixed anything.

Is there anything in dmesg that would indicate that your hard drive is properly recognized. Also why ext2? It's obsolete and has been superseeded by ext3 and ext4!
 
> What linux do you used for compiling this kernel?

Whatever Fedora version was available in 2019.

**Comment by kaxapo** [comment]
1: did you get any errors when compiling the kernel on Fedora? Any errors when executing (make and make install) ? 

2: so you did install this on a jailbroken freebox v4 or v5 i guess?

**Comment by jeanthom** [comment]
> 1: did you get any errors when compiling the kernel on Fedora? Any errors when executing (make and make install) ?

None that I can think of.
EDIT: Why would you run make install?

> 2: so you did install this on a jailbroken freebox v4 or v5 i guess?

Nope, this is a kernel for the Freebox Revolution (v6). v4/v5 have a different system-on-chip (BCM6348). And as far as I know, there's no Freebox jailbreak currently.

**Comment by kaxapo** [comment]
1: how i will install the kernel without running "make install" then? 

2: can you explain me the procedure you did to install the kernel? So i can try it ?

**Comment by jeanthom** [comment]
I think I understand what you are trying to achieve and how you intend to do it. Installing Linux on a Freebox is _much_ different than installing Linux on a regular PC. The boot process is different, and it's not just a matter of putting the Linux kernel binary on a hard drive in the right place (which is what a `make install` usually does).

Now I'm not going to explain publicly all the steps required to sideload a third-party operating system on a Freebox. This is not even useful anyway: the Freebox Revolution is 10 years old, has an old ARM ISA that nobody bothers to compile to anymore, etc.

I think I have spent enough time answering your questions and will be closing this issue. If you want to learn more about embedded Linux, I would invite you to grab a cheap ARM development board (Pine64, Olimex, Beaglebone, Raspberry Pi, etc.) and try following a tutorial that guides you through the U-Boot/Linux/ramfs cross-compilation and install process.
